### ISSUE TITLE
Regression - The height is not adapted to the content of the tile

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-adaptor-sched#31]
This happens with latest android build. If the sched venue only have one or two events, the tile is shown in a square bigger than its content.
Please see image below.
![screenshot](https://cloud.githubusercontent.com/assets/1897507/15923709/d0980a16-2e2e-11e6-8f67-8c3cc10ea04e.png)

**Comment by arcturus** [comment]
@isabelrios was this happening without the last commit that @wilsonpage added yesterday about height?

**Comment by isabelrios** [comment]
@arcturus I downloaded today nightly build and it is where I saw it, so I guess that build has that commit.

**Comment by samgiles** [comment]
Filed https://github.com/mozilla-magnet/magnet-client/issues/142 - this
should make figuring out cases like this easier.

**Comment by isabelrios** [comment]
I should have commented this before, but opened the bug here because this is only happening to me with sched tiles, the others are correctly sized.

**Comment by wilsonpage** [comment]
closes by 491f21ce07bd9f8ada7751ee3eb16611c1f7c877

**Comment by wilsonpage** [comment]
The reasons this was happening is because we were telling the tile to be 300x300 size via the oembed.json. Then once the webview content was measured it was correctly returning 300 as a document, even though the tile content is only 200px tall.

I removed the width/height properties from the oembed.json so that now the height is based purely on then content measurement.

**Comment by isabelrios** [comment]
Cool! this is fine now :)
